### ISSUE TITLE
Remove node-fetch change to another fetch package

### ISSUE THREAD

**Issue by Sirherobrine23** [The-Bds-Maneger/Bds-Maneger-Core#179]
With the new version of node-fetch that is forcing many projects to use ESM for their own interests, we like ESM, but we won't mind ESM anytime soon.

Bds Maneger will still be programmed in CJS, even when NodeJS officially switches to ESM then we will be concerned about bringing Bds Maneger Core to ESM.

Tasks:
- [x] Install axios.
- [x] Install node-fetch@3
- [x] Resolve requests in node-fetch
- [x] Resolve requests in axios

**Comment by jimmywarting** [comment]
you could also just pin/stick with v2 of node-fetch
i would recommend keep using the fetch api, it's going to be introduced to nodejs core one day

the alternative is that you use the async import solution.
```js
const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));
```
